# Generated by Django 3.2.5 on 2021-08-05 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventomodel',
            name='aprovado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='eventomodel',
            name='comissao',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
