# Generated by Django 3.2.5 on 2021-08-05 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0002_auto_20210805_1818'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventomodel',
            name='advertising',
            field=models.ImageField(default=1, upload_to='eventos/advertising/', verbose_name='Propaganda'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='eventomodel',
            name='img',
            field=models.ImageField(default=1, upload_to='eventos/media/', verbose_name='Imagem'),
            preserve_default=False,
        ),
    ]
