# Generated by Django 3.2.5 on 2021-08-06 17:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('eventos', '0005_eventomodel_tipo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fornecedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=155)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('type', models.CharField(max_length=155)),
                ('status', models.CharField(choices=[('1', 'Aberto'), ('2', 'Pago'), ('3', 'Atrazo')], max_length=1)),
                ('data', models.CharField(max_length=10)),
                ('banco_nome', models.CharField(max_length=155)),
                ('conta', models.IntegerField()),
                ('agencia', models.IntegerField()),
                ('digito', models.IntegerField()),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eventos.eventomodel')),
            ],
        ),
    ]
